#! /bin/bash

_cli_bash_autocomplete() {
     local cur prev opts base
     COMPREPLY=()
     cur="${COMP_WORDS[COMP_CWORD]}"
     prev="${COMP_WORDS[COMP_CWORD-1]}"
     #opts=$( ${COMP_WORDS[@]:0:$COMP_CWORD} --generate-bash-completion )
     opts="associate associated backup console dashboard db default disassociate environments logs logout metrics rake redeploy ssl status support-ids users vars version whoami worker"
     COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
     return 0
 }

 complete -F _cli_bash_autocomplete catalyze
